### ISSUE TITLE
TTL trigger

### ISSUE THREAD

**Issue by BenInglis** [Brain-Imaging-Center/EEG-fMRI#1]
From Arielle Tambini:

"Would it be possible to have another bnc output that conveys the scanner TTLs? This additional bnc out is taken in by the 'syncbox', a piece of hardware that interfaces with the computer running the software for EEG data acquisition (it is supposed to synchronize EEG acquisition with the scanner using the TTL)."

We first need to determine whether the 60 ms extended TTL we use for all the existing peripherals will also trigger the EEG properly.

**Comment by danshel** [comment]
Note that there is already in place a T-connector to channel the TTL to a second device (We are using it for TMS triggering when needed).

**Comment by danshel** [comment]
The T-connector is on the aluminum box and it delivers a 10 usec TTL pulse.

**Comment by danshel** [comment]
Another T-connector could be placed on the blue box if a 60ms TTL is needed.

**Comment by BenInglis** [comment]
Grand! Thanks. Okay, so we have both 10 us option now and a 60 ms option can be added easily. I'll close this issue.
